### ISSUE TITLE
Flatpak manifest

### ISSUE THREAD

**Issue by JakobDev** [autokey/autokey#710]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

Qt

### Anything else?

I have created a Flatpak manifest for the Qt Gui: Crate this 2 files:

com.github.autokey.autokey.yaml:
```yaml
app-id: com.github.autokey.autokey
runtime: org.kde.Platform
runtime-version: '5.15-21.08'
sdk: org.kde.Sdk
base: com.riverbankcomputing.PyQt.BaseApp
base-version: '5.15-21.08'
command: autokey-qt
cleanup-commands:
  - /app/cleanup-BaseApp.sh
build-options:
  env:
    - BASEAPP_REMOVE_PYWEBENGINE=1
finish-args:
  - --socket=session-bus
  - --socket=x11
  - --share=network
  - --device=dri
  - --share=ipc

modules:
  - python3-modules.yaml

  - name: qscintilla
    buildsystem: simple
    build-commands:
      - sip-install --target-dir=/app/lib/python/site-packages/ --verbose --debug
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/da/94/2151c916a711914f1aa3c5c45a6a67aebfdc2a1c5ca0b82d2d09efe7e833/QScintilla-2.13.3.tar.gz
        sha256: 92ae5bf066e0bcb79f0c1df255882189b66c200f92f08ca14f09b82479469dce
        x-checker-data:
            type: pypi
            name: QScintilla
            packagetype: sdist

  - name: kdialog
    buildsystem: cmake
    sources:
      - type: git
        url: https://invent.kde.org/utilities/kdialog.git

  - name: libxmu
    sources:
      - type: git
        url: git://anongit.freedesktop.org/git/xorg/lib/libXmu
        tag: libXmu-1.1.3

  - name: wmctrl
    sources:
      - type: archive
        url: http://tripie.sweb.cz/utils/wmctrl/dist/wmctrl-1.07.tar.gz
        sha256: d78a1efdb62f18674298ad039c5cbdb1edb6e8e149bb3a8e3a01a4750aa3cca9

  - name: autokey
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
    sources:
      - type: git
        url: https://github.com/autokey/autokey.git
```

python3-modules.yaml:
```yaml
build-commands: []
buildsystem: simple
modules:
  - name: python3-dbus-python
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "dbus-python" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/b1/5c/ccfc167485806c1936f7d3ba97db6c448d0089c5746ba105b6eb22dba60e/dbus-python-1.2.18.tar.gz
        sha256: 92bdd1e68b45596c833307a5ff4b217ee6929a1502f5341bae28fd120acf7260
        x-checker-data:
          name: dbus-python
          type: pypi
  - name: python3-pyinotify
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "pyinotify" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz
        sha256: 9c998a5d7606ca835065cdabc013ae6c66eb9ea76a00a1e3bc6e0cfe2b4f71f4
        x-checker-data:
          name: pyinotify
          type: pypi
  - name: python3-python-xlib
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "python-xlib" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/c2/16/950463d36e8b64067c4d535038c5512de8200015e793d7d0a3f400187cbf/python_xlib-0.31-py2.py3-none-any.whl
        sha256: 1ec6ce0de73d9e6592ead666779a5732b384e5b8fb1f1886bd0a81cafa477759
        x-checker-data:
          name: python_xlib
          packagetype: bdist_wheel
          type: pypi
  - name: python3-pyhamcrest
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "pyhamcrest" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/5a/fa/488920633f45c1c291c633fcbe0cd465f40d91ac2a2b90f594bae36db80a/PyHamcrest-2.0.3-py3-none-any.whl
        sha256: c29dc977154c49e17c30d1ed49a0a6e31cb0dc7bcf733ac4aa9cb58519c2b00c
        x-checker-data:
          name: PyHamcrest
          packagetype: bdist_wheel
          type: pypi
name: python3-modules
```

Install everything that is needed to build:
```bash
flatpak install org.kde.Platform//5.15-21.08 org.kde.Sdk//5.15-21.08 com.riverbankcomputing.PyQt.BaseApp//5.15-21.08 org.flatpak.Builder
```

Build:
```bash
flatpak run org.flatpak.Builder build-dir com.github.autokey.autokey.yaml --force-clean --ccache --install --user
```

Run:
```bash
flatpak run com.github.autokey.autokey
```

This still needs work, but the basics are working. Tell me if you are interested, so I can go further.
